### ISSUE TITLE
字体导致界面错乱

### ISSUE THREAD

**Issue by IanSung** [404name/winter#2]
不同的字体会导致布局错乱。

**Comment by 404name** [comment]
改成
GBK吧。这个没办法的不同编码有些字符长度不同




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HaicSong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 中午11:19
收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[404name/winter] 字体导致界面错乱 (#2)




不同的字体会导致布局错乱。

**Comment by IanSung** [comment]
> 改成 GBK吧。这个没办法的不同编码有些字符长度不同
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"HaicSong"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月7日(星期六) 中午11:19 收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[404name/winter] 字体导致界面错乱 (#2) 不同的字体会导致布局错乱。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已经是GBK了，可能是我系统的问题。

**Comment by 404name** [comment]
噢，刚刚遇到了几个和你情况一样的了，win7的旧版控制台的问题，我写的时候以为是编码问题，其实还是控制台的问题。只能是win10的gbk才能显示 ‘-’是占1个字节长度的。抱歉了，没办法解决，只有win10才能正常显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HaicSong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 下午3:13
收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;;
抄送:&nbsp;"=￣ω￣="<1308964967@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [404name/winter] 字体导致界面错乱 (#2)



 
改成 GBK吧。这个没办法的不同编码有些字符长度不同
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"HaicSong"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月7日(星期六) 中午11:19 收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[404name/winter] 字体导致界面错乱 (#2) 不同的字体会导致布局错乱。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
已经是GBK了，可能是我系统的问题。

**Comment by 404name** [comment]
已解决0v0 o(￣▽￣)ｄ

**Comment by ChenXinXuTUSC** [comment]
作者太强了吧！
整个TXT文档里面的代码感觉挺规范的，看起来很舒服，注释也写了很多，爱了，请问作者是参加工作了还是在读书呢，我是大一新生，没写过超过１０００行的小ｄｅｍｏ，但是平时自己也会偶尔写写贪吃蛇那些小游戏，总之作者太强了，关注了

**Comment by 404name** [comment]
但我的变量命名还是有点随意，反倒需要很多注释去说明，毕竟英语不太好，哈哈qwq。我也是大一在读，差不多也喜欢写写小游戏，就平时喜欢随便玩玩，所以也不是很精通啦0.0。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Karen-Cyber"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 下午2:48
收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;;
抄送:&nbsp;"=￣ω￣="<1308964967@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [404name/winter] 字体导致界面错乱 (#2)





 
作者太强了吧！
 整个TXT文档里面的代码感觉挺规范的，看起来很舒服，注释也写了很多，爱了，请问作者是参加工作了还是在读书呢，我是大一新生，没写过超过１０００行的小ｄｅｍｏ，但是平时自己也会偶尔写写贪吃蛇那些小游戏，总之作者太强了，关注了

**Comment by joy-G-hub** [comment]
希望大佬能分享一下学习经验
